Areas/LOC_State/Controllers/StateController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using StudentRegistration.Areas.LOC_State.Models;
using StudentRegistration.Areas.LOC_Country.Models;

namespace StudentRegistration.Areas.LOC_State.Controllers
{
    [Area("LOC_State")]
    public class StateController : Controller
    {
        private IConfiguration Configuration;
        private object searchCountry;

        public int StateID { get; private set; }

        public StateController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult StateList(SearchStateModel srs)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            DataTable dt = new DataTable();
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand objcmd = conn.CreateCommand();
            objcmd.CommandType = CommandType.StoredProcedure;
            objcmd.CommandText = "PR_State_SerchByStateCodeOrStateName";
            objcmd.Parameters.AddWithValue("@StateName", srs.StateName);
            objcmd.Parameters.AddWithValue("@StateCode", srs.StateCode);
            objcmd.Parameters.AddWithValue("@CountryName", srs.CountryName);

            SqlDataReader objSDR = objcmd.ExecuteReader();
            dt.Load(objSDR);
            return View("StateList", dt);
        }
        public IActionResult DeleteState(int StateID)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand objcmd = conn.CreateCommand();
            objcmd.CommandType = CommandType.StoredProcedure;
            objcmd.CommandText = "PR_State_DeleteByPK ";
            objcmd.Parameters.AddWithValue("@StateID", StateID);
            objcmd.ExecuteReader();
            conn.Close();
            return RedirectToAction("StateList");
        }


        public IActionResult AddState(int StateID)

        {
            StateDropdown(StateID);

            if (StateID != 0)
            {
                ViewBag.Data = StateID;
                try
                {

                    string str = this.Configuration.GetConnectionString("myConnectionString");
                    DataTable dt = new DataTable();
                    SqlConnection conn = new SqlConnection(str);
                    conn.Open();
                    SqlCommand objcmd = conn.CreateCommand();
                    objcmd.CommandType = CommandType.StoredProcedure;
                    objcmd.CommandText = "PR_STATE_SELECTBYPK";
                    objcmd.Parameters.AddWithValue("@StateID", StateID);
                    SqlDataReader objDataReader = objcmd.ExecuteReader();
                    dt.Load(objDataReader);
                    conn.Close();
                    LOC_StateModel LC = new LOC_StateModel
                    {
                        StateID = (int)dt.Rows[0]["StateID"],
                        StateName = (string)dt.Rows[0]["StateName"],
                        StateCode = (string)dt.Rows[0]["StateCode"],
                        CountryID = (int)dt.Rows[0]["CountryID"]
                    };
                    return View(LC);
                }
                catch (Exception ex)
                {
                    return View();
                }
            }
            else
            {
                return View();
            }

        }
        public IActionResult Save(LOC_StateModel StateModel)
        {
            try
            {
                String connectionStr = this.Configuration.GetConnectionString("myConnectionString");
                SqlConnection conn = new SqlConnection(connectionStr);
                conn.Open();
                SqlCommand objcmd = conn.CreateCommand();
                objcmd.CommandType = CommandType.StoredProcedure;
                if (StateModel.StateID != 0)
                {
                    objcmd.CommandText = "PR_state_UpdateByPK";
                    objcmd.Parameters.AddWithValue("@StateID", StateModel.StateID);
                }
                else
                {
                    objcmd.CommandText = "PR_State_Insert";
                }
                objcmd.Parameters.AddWithValue("@StateName", StateModel.StateName);
                objcmd.Parameters.AddWithValue("@StateCode", StateModel.StateCode);
                objcmd.Parameters.AddWithValue("@CountryID", StateModel.CountryID);
                objcmd.ExecuteReader();
                conn.Close();
                return RedirectToAction("StateList");
            }
            catch (Exception ex)
            {
                return RedirectToAction("StateList");
            }
        }
        public IActionResult StateDropdown(int  StateID)
        {
            SqlConnection sqlConnection = new SqlConnection(this.Configuration.GetConnectionString("myConnectionString"));
            sqlConnection.Open();
            SqlCommand cmd = sqlConnection.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_STATE_SELECTBYPK";
            cmd.Parameters.AddWithValue("@StateID", StateID);
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);

            LOC_StateModel stateModel  = new LOC_StateModel();
            foreach(DataRow row in dt.Rows)
            {
                stateModel.StateID = int.Parse(row["StateID"].ToString());
                stateModel.StateName = row["StateName"].ToString();
                stateModel.StateCode = row["StateCOde"].ToString();
                stateModel.CountryID = int.Parse(row["CountryID"].ToString());
            }
            SqlCommand sqlCommand2 = sqlConnection.CreateCommand();
            sqlCommand2.CommandType = CommandType.StoredProcedure;
            sqlCommand2.CommandText = "PR_COUNTRY_SELECTALL";
            SqlDataReader sqlDataReader = sqlCommand2.ExecuteReader();
            DataTable dt1 = new DataTable();
            dt1.Load(sqlDataReader);
            
            List<LOC_CountryModel> li = new List<LOC_CountryModel>();
            foreach(DataRow dr in dt1.Rows)
            {
                LOC_CountryModel lOC_CountryModel = new LOC_CountryModel();
                lOC_CountryModel.CountryID = int.Parse(dr["CountryID"].ToString());
                lOC_CountryModel.CountryName = dr["CountryName"].ToString();
                li.Add(lOC_CountryModel);
            }
            ViewBag.LI = li;
            sqlConnection.Close();
            return View(stateModel);
        }

    }
}

Areas/LOC_State/Views/State/AddState.cshtml
@using StudentRegistration.Areas.LOC_Country.Models;
@{
    ViewData["Title"] = "Add Country";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model StudentRegistration.Areas.LOC_State.Models.LOC_StateModel

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<h3>State Add/Edit</h3>
<div class="col-lg-6">

    <div class="card">
        <div class="card-body">
                <style>
                    .form-group label::before {
                        content: "*";
                        color: red;
                    }
                </style>
            <!-- Vertical Form -->
            <form class="row g-3" method="post" asp-area="LOC_State" asp-controller="State" asp-action="Save">
                    <div class="form-group">
                    <label>State Name</label>
                    <input asp-for="StateName" type="text" placeholder="State Name" class="form-control" /><br />
                    <span class="text-danger" asp-validation-for="StateName"></span>
                </div>
                <div class="form-group">
                    <label for="inputEmail4" class="form-label">State Code</label>
                    <input asp-for="StateCode" type="text" placeholder="State Code" class="form-control"/><br />
                    <span class="text-danger" asp-validation-for="StateCode"></span>
                </div>
                <div class="form-group">
                    <label for="inputEmail4" class="form-label">Country Name</label>
                    <select asp-for="CountryID" class="form-control">
                        <option>Select Country</option>
                        @foreach (LOC_CountryModel lc in ViewBag.LI)
                        {
                            <option value="@lc.CountryID">@lc.CountryName</option>
                        }
                    </select>
                </div>

                <div class="text-center">
                    <input type="hidden" name="StateID" value="@Model.StateID" />
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form><!-- Vertical Form -->
            </div>
        </div>
    </div>

Areas/LOC_State/Views/State/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>hii</h1>

Areas/LOC_State/Views/State/StateList.cshtml
@{
    ViewData["Title"] = "List Country";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data
@model DataTable

<h3>State List</h3>
<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <div class="container-fluid">
                        <a class="navbar-brand">State Search</a>
                        <form class="d-flex w-75" role="search" asp-area="LOC_State" asp-controller="State" asp-action="StateList">
                            <input class="form-control me-2" type="text" placeholder="State Name" aria-label="Search" name="StateName">
                            <input class="form-control me-2" type="text" placeholder="State Code" aria-label="Search" name="StateCode">
                            <input class="form-control me-2" type="text" placeholder="Country Name" aria-label="Search" name="CountryName">

                            <button class="btn btn-outline-success" type="submit">Search</button>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                            <a class=" btn btn-primary col-md-3" asp-area="LOC_State" asp-controller="State" asp-action="AddState">Add State</a>

                        </form>
                    </div>

                    <!-- Table with stripped rows -->
                    <table class="table datatable">
                        <thead>
                            <tr>
                                <th scope="col">StateID</th>
                                <th scope="col">StateName</th>
                                <th scope="col">StateCode</th>
                                <th scope="col">CountryName</th>
                                <th scope="col">Add Date</th>
                                <th scope="col">MOdifi Date</th>
@*                                 <th scope="col">CityCount</th>
 *@                                <th scope="col">Delete</th>
                                <th scope="col">Edit</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (DataRow dr in Model.Rows)
                            {
                                <tr>
                                    <td>@dr["StateID"]</td>
                                    <td>@dr["StateName"]</td>
                                    <td>@dr["Statecode"]</td>

                                    <td>@dr["CountryName"]</td>
                                    <td>@Convert.ToDateTime(dr["Created"])</td>
                                    <td>@Convert.ToDateTime(dr["Modified"])</td>
@*                                     <td>@dr["CityCount"]</td>
 *@                                    <td>
                                        <form method="post" asp-area="LOC_State" asp-controller="State" asp-action="DeleteState">
                                            <input type="hidden" name="StateID" value="@Convert.ToInt32(dr["StateID"])" />
                                            <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                        </form>
                                    </td>
                                    <td>
                                        <form method="post" asp-area="LOC_State" asp-controller="State" asp-action="AddState">
                                            <input type="hidden" name="StateID" value="@Convert.ToInt32(dr["StateID"])" />
                                            <button type="submit" class="btn btn-outline-warning">Edit</button>
                                        </form>
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->

                </div>
            </div>

        </div>
    </div>
</section>