Areas/MST_Branch/Controllers/BranchController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using StudentRegistration.Areas.MST_Branch.Models;
using StudentRegistration.Areas.LOC_Country.Models;

namespace StudentRegistration.Areas.MST_Branch.Controllers
{
    [Area("MST_Branch")]
    public class BranchController : Controller
    {
        private IConfiguration Configuration;
        public BranchController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult BranchList(SearchBranchModel searchBranch)

        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            DataTable dt = new DataTable();
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand objcmd = conn.CreateCommand();
            objcmd.CommandType = CommandType.StoredProcedure;
            objcmd.CommandText = "PR_Branch_SerchByBranchCodeOrBranchName";
            objcmd.Parameters.AddWithValue("@BranchName", searchBranch.BranchName);
            objcmd.Parameters.AddWithValue("@BranchCode", searchBranch.BranchCode);
            SqlDataReader objSDR = objcmd.ExecuteReader();
            dt.Load(objSDR);
            return View("BranchList", dt);
        }
        public IActionResult DeleteBranch(int BranchID)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand objcmd = conn.CreateCommand();
            objcmd.CommandType = CommandType.StoredProcedure;
            objcmd.CommandText = "PR_Branch_DeleteByPK ";
            objcmd.Parameters.AddWithValue("@BranchID", BranchID);
            objcmd.ExecuteReader();
            conn.Close();
            return RedirectToAction("BranchList");
        }

        public IActionResult AddBranch(int BranchID)

        {
            if (BranchID != 0)
            {
                ViewBag.Data = BranchID;
                try
                {

                    string str = this.Configuration.GetConnectionString("myConnectionString");
                    DataTable dt = new DataTable();
                    SqlConnection conn = new SqlConnection(str);
                    conn.Open();
                    SqlCommand objcmd = conn.CreateCommand();
                    objcmd.CommandType = CommandType.StoredProcedure;
                    objcmd.CommandText = "PR_Branch_SELECTByPK";
                    objcmd.Parameters.AddWithValue("@BranchID", BranchID);
                    SqlDataReader objDataReader = objcmd.ExecuteReader();
                    dt.Load(objDataReader);
                    conn.Close();
                    MST_BranchModel LC = new MST_BranchModel
                    {
                        BranchID = (int)dt.Rows[0]["BranchID"],
                        BranchName = (string)dt.Rows[0]["BranchName"],
                        BranchCode = (string)dt.Rows[0]["BranchCode"]
                    };
                    return View(LC);
                }
                catch (Exception ex)
                {
                    return View();
                }
            }
            else
            {
                return View();
            }

        }
        public IActionResult Save(MST_BranchModel BranchModel)
        {
            try
            {
                String connectionStr = this.Configuration.GetConnectionString("myConnectionString");
                SqlConnection conn = new SqlConnection(connectionStr);
                conn.Open();
                SqlCommand objcmd = conn.CreateCommand();
                objcmd.CommandType = CommandType.StoredProcedure;
                if (BranchModel.BranchID != 0)
                {
                    objcmd.CommandText = "PR_Branch_UpdateBy_PK";
                    objcmd.Parameters.AddWithValue("@BranchID", BranchModel.BranchID);
                }
                else
                {
                    objcmd.CommandText = "PR_Branch_Insert";
                }
                objcmd.Parameters.AddWithValue("@BranchName", BranchModel.BranchName);
                objcmd.Parameters.AddWithValue("@BranchCode",BranchModel.BranchCode);
                objcmd.ExecuteReader();
                conn.Close();
                return RedirectToAction("BranchList");
            }
            catch (Exception ex)
            {
                return RedirectToAction("BranchList");
            }
        }


    }
}

Areas/MST_Branch/Views/Branch/AddBranch.cshtml
@{
    ViewData["Title"] = "Add Branch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model StudentRegistration.Areas.MST_Branch.Models.MST_BranchModel

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<h3>Branch Add/Edit</h3>
<div class="col-lg-6">

    <div class="card">
        <div class="card-body">

            <!-- Vertical Form -->
            <form class="row g-3" method="post" asp-area="MST_Branch" asp-controller="Branch" asp-action="Save">
                <input type="hidden" asp-for="BranchID" />

                <div class="col-12">
                    <label for="inputNanme4" class="form-label">Branch Name</label>
                    <input type="text" class="form-control" asp-for="BranchName" placeholder="Branch Name">
                    <span class="text-danger" asp-validation-for="BranchName"></span>
                </div>
                <div class="col-12">
                    <label for="inputEmail4" class="form-label">Branch Code</label>
                    <input type="text" class="form-control" asp-for="BranchCode" placeholder="Branch code">
                    <span class="text-danger" asp-validation-for="BranchCode"></span>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form><!-- Vertical Form -->

        </div>
    </div>

Areas/MST_Branch/Views/Branch/BranchList.cshtml
@{
    ViewData["Title"] = "List Country";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data
@model DataTable
 
<h3>Branch List</h3>

<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <div class="container-fluid">
                        <a class="navbar-brand">Branch Search</a>
                        <form class="d-flex w-75" role="search" asp-area="MST_Branch" asp-controller="Branch" asp-action="BranchList">
                            <input class="form-control me-2" type="text" placeholder="Branch Name" aria-label="Search" name="BranchName">
                            <input class="form-control me-2" type="text" placeholder="Branch Code" aria-label="Search" name="BranchCode">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <a class=" btn btn-primary col-md-3" asp-area="MST_Branch" asp-controller="Branch" asp-action="AddBranch">Add Branch</a>

                        </form>
                    </div>

                       
                    </div>

                    <!-- Table with stripped rows -->
                    <table class="table datatable">
                        <thead>
                            <tr>
                            <th scope="col">BranchID</th>
                            <th scope="col">BranchName</th>
                            <th scope="col">BranchCode</th>
                            <th scope="col">Created</th>
                            <th scope="col">ModifiDate</th>

                            <th scope="col">Delete</th>
                            <th scope="col">Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach (DataRow dr in Model.Rows)
                        {
                            <tr>
                                <td>@dr["BranchID"]</td>
                                <td>@dr["BranchName"]</td>
                                <td>@dr["BranchCode"]</td>
                                <td>@Convert.ToDateTime(dr["Created"])</td>
                                <td>@Convert.ToDateTime(dr["Modified"])</td>
                                <td>
                                    <form method="post" asp-area="MST_Branch" asp-controller="Branch" asp-action="DeleteBranch">
                                        <input type="hidden" name="BranchID" value="@Convert.ToInt32(dr["BranchID"])" />
                                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                    </form>
                                </td>
                                <td>
                                    <form method="post" asp-area="MST_Branch" asp-controller="Branch" asp-action="AddBranch">
                                        <input type="hidden" name="BranchID" value="@Convert.ToInt32(dr["BranchID"])" />
                                        <button type="submit" class="btn btn-outline-warning">Edit</button>
                                    </form>
                                </td>

                            </tr>
                        }



                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->

                </div>
            </div>

        </div>
    </div>
</section>