Areas/LOC_Country/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using StudentRegistration.Areas.LOC_Country.Models;
using System.Data;
using System.Data.SqlClient;

namespace StudentRegistration.Areas.LOC_Country.Controllers
{
    [Area("LOC_Country")]

    public class CountryController : Controller
    {

        private IConfiguration Configuration;  
      public CountryController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CountryList(SearchCountryModel searchCountry)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            DataTable dt = new DataTable();
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand objcmd = conn.CreateCommand();
            objcmd.CommandType = CommandType.StoredProcedure;
            objcmd.CommandText = "PR_LOC_Country_Search";
            objcmd.Parameters.AddWithValue("@CountryName", searchCountry.CountryName);
            objcmd.Parameters.AddWithValue("@CountryCode", searchCountry.CountryCode);
            SqlDataReader objSDR = objcmd.ExecuteReader();
            dt.Load(objSDR);
            return View("CountryList",dt);
        }
        public IActionResult DeleteCountry(int CountryID)
        {
            string str = this.Configuration.GetConnectionString("myConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand objcmd = conn.CreateCommand();
            objcmd.CommandType = CommandType.StoredProcedure;
            objcmd.CommandText = "PR_COUNTRY_Delete ";
            objcmd.Parameters.AddWithValue("@CountryID", CountryID);
            objcmd.ExecuteReader();
            conn.Close();
            return RedirectToAction("CountryList");
        }
        public IActionResult AddCountry(int CountryID)
        {
            if(CountryID != 0)
            {
                ViewBag.Data = CountryID;
                try
                {

                    string str = this.Configuration.GetConnectionString("myConnectionString");
                    DataTable dt = new DataTable();
                    SqlConnection conn = new SqlConnection(str);
                    conn.Open();
                    SqlCommand objcmd = conn.CreateCommand();
                    objcmd.CommandType = CommandType.StoredProcedure;
                    objcmd.CommandText = "PR_COUNTRY_SELECTByPK";
                    objcmd.Parameters.AddWithValue("@CountryID", CountryID);
                    SqlDataReader objDataReader = objcmd.ExecuteReader();
                    dt.Load(objDataReader);
                    conn.Close();
                    LOC_CountryModel LC = new LOC_CountryModel
                    {
                        CountryID = (int)dt.Rows[0]["CountryID"],
                        CountryName = (string)dt.Rows[0]["CountryName"],
                        CountryCode = (string)dt.Rows[0]["CountryCode"]
                    };
                    return View(LC);
                }
                catch(Exception ex)
                {
                    return View();
                }
            }
            else
            {
                return View();
            }

        }

        public IActionResult Save(LOC_CountryModel CountryModel)
        {
            try
            {
                String connectionStr = this.Configuration.GetConnectionString("myConnectionString");
                SqlConnection conn = new SqlConnection(connectionStr);
                conn.Open();
                SqlCommand objcmd = conn.CreateCommand();
                objcmd.CommandType = CommandType.StoredProcedure;
                if (CountryModel.CountryID != 0)
                {
                    objcmd.CommandText = "PR_Country_Update";
                    objcmd.Parameters.AddWithValue("@CountryID", CountryModel.CountryID);
                }
                else
                {
                    objcmd.CommandText = "PR_Country_Insert";
                }
                objcmd.Parameters.AddWithValue("@CountryName", CountryModel.CountryName);
                objcmd.Parameters.AddWithValue("@CountryCode", CountryModel.CountryCode);
                objcmd.ExecuteReader();
                conn.Close();
                return RedirectToAction("CountryList");
            }
            catch (Exception ex)
            {
                return RedirectToAction("CountryList");
            }
        }
    }
}

Areas/LOC_Country/Views/Country/AddCountry.cshtml
@{
    ViewData["Title"] = "Add Country";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model StudentRegistration.Areas.LOC_Country.Models.LOC_CountryModel

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<h3>Country Add/Edit</h3>
<div class="col-lg-6">

    <div class="card">
        <div class="card-body">

            <!-- Vertical Form -->
            <form class="row g-3" method="post" asp-area="LOC_Country" asp-controller="Country" asp-action="Save">
                <div class=" form-group">
                    <style>
                        .form-group label::before {
                            content: "*";
                            color: red;
                        }
                    </style>
                    <input type="hidden" name="CountryID" asp-for="CountryID" />

                    <label>Country Name</label>
                    <input type="text" class="form-control" asp-for="CountryName" placeholder="Country Name">

                    <span class="text-danger" asp-validation-for="CountryName"></span>

                </div>
                <div class="form-group">
                    <label for="inputEmail4" class="form-label">Country Code</label>
                    <input type="text" class="form-control" asp-for="CountryCode" placeholder="Country Code">
                    <span class="text-danger" asp-validation-for="CountryCode"></span>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form><!-- Vertical Form -->

        </div>
    </div>

Areas/LOC_Country/Views/Country/CountryList.cshtml
@{
    ViewData["Title"] = "List Country";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data
@model DataTable
<h3>Country List</h3>

<section class="section">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">
                    <div class="container-fluid">
                        <a class="navbar-brand">Country Search</a>

                        <form class="d-flex w-75" role="search" asp-area="LOC_Country" asp-controller="Country" asp-action="CountryList">
                            <input class="form-control me-2 " type="text" placeholder="Country Name" aria-label="Search" name="CountryName">
                            <input class="form-control me-2" type="text" placeholder="Country Code" aria-label="Search" name="CountryCode">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


                            <a class=" btn btn-primary col-md-3" asp-area="LOC_Country" asp-controller="Country" asp-action="AddCountry">Add Country</a>

                        </form>
                    </div>

<!-- Table with stripped rows -->
                    <table class="table datatable">
                        <thead>
                            <tr>
                                <th scope="col">CountryID</th>
                                <th scope="col">CountryName</th>
                                <th scope="col">CountryCode</th>
                                <th scope="col">Add Date</th>
                                <th scope="col">Modifi Date</th>
                              @*   <th scope="col">StateCount</th>

                                <th scope="col">CityCount</th>
                               *@  <th scope="col">Delete</th>
                                <th scope="col">Edit</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (DataRow dr in Model.Rows)
                            {
                                <tr>
                                    <td>@dr["CountryID"]</td>
                                    <td>@dr["CountryName"]</td>
                                    <td>@dr["Countrycode"]</td>
                                    <td>@Convert.ToDateTime(dr["Created"])</td>
                                    <td>@Convert.ToDateTime(dr["Modified"])</td>
                                  @*   <td>@dr["StateCount"]</td>
                                    <td>@dr["CityCount"]</td>
                                   *@  <td>
                                        <form method="post" asp-area="LOC_Country" asp-controller="Country" asp-action="DeleteCountry">
                                            <input type="hidden" name="CountryID" value="@Convert.ToInt32(dr["CountryID"])" />
                                            <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                        </form>
                                    </td>
                                    <td>
                                        <form method="post" asp-area="LOC_Country" asp-controller="Country" asp-action="AddCountry">
                                            <input type="hidden" name="CountryID" value="@Convert.ToInt32(dr["CountryID"])" />
                                            <button type="submit" class="btn btn-outline-warning btn-sm">Edit</button>
                                        </form>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                    <!-- End Table with stripped rows -->

                </div>
            </div>

        </div>
    </div>
</section>